version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      website-deps:
        patterns:
          - "*"

  - package-ecosystem: pub
    directory: /mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      mobile-deps:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      server-deps:
        patterns:
          - "*"
