changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - dependencies
        - security
        - ci
        - docs
        - chore
    - title: Other Changes
      labels:
        - '*'
